### ISSUE TITLE
Any funkiness in the ssh binary?

### ISSUE THREAD

**Issue by singpolyma** [BGmot/BGShellBB10#10]
Trying to use the ssh binary from this app with other terminals also. It works, but there is weirdness. Sometimes seems to hang in other terminal and if I open this app the password prompt shows in this app. Then have to close both apps and try the other again and it will sometimes work. Is the tty hardcoded or similar?

**Comment by BGmot** [comment]
I am afraid I don't understand what you are trying to do. Tty is indeed hardcoded https://github.com/BGmot/BGShellBB10/blob/master/main.cpp#L107

**Comment by singpolyma** [comment]
I meant in the ssh binary. But I've gotten a vanilla cross-compiled openssh now which seems to work, so this is less relevant :) Thanks
